git add Acerva.Infra/Acerva.Infra.csproj
git add Acerva.Infra/Repositorios/CadastroUsuarios.cs
git add Acerva.Infra/Repositorios/ICadastroUsuarios.cs
git add Acerva.Modelo.Mapeamento/Acerva.Modelo.Mapeamento.csproj
git add Acerva.Modelo.Mapeamento/UsuarioClassMap.cs
git add Acerva.Modelo/Acerva.Modelo.csproj
git add Acerva.Modelo/Usuario.cs
git add Acerva.Web/Acerva.Web.csproj
git add Acerva.Web/App_Start/BundleConfig.cs
git add Acerva.Web/Content/Aplicacao/css/site.less
git add Acerva.Web/Controllers/AccountController.cs
git add Acerva.Web/Controllers/RegionalController.cs
git add Acerva.Web/Controllers/SituacaoController.cs
git add Acerva.Web/Controllers/UsuarioController.cs
git add Acerva.Web/Global.asax.cs
git add Acerva.Web/Models/CadastroUsuarios/UsuarioViewModel.cs
git add Acerva.Web/Models/Home/UsuarioRegistroViewModel.cs
git add Acerva.Web/Ninject/RepositoriosNoBancoDeDadosNinjectModule.cs
git add Acerva.Web/Properties/AssemblyInfo.cs
git add Acerva.Web/Scripts/Aplicacao/Regional/acerva.regional.controller.js
git add Acerva.Web/Scripts/Aplicacao/Situacao/acerva.situacao.controller.js
git add Acerva.Web/Scripts/Aplicacao/Situacao/acerva.situacao.service.js
git add Acerva.Web/Scripts/Aplicacao/Usuario/acerva.usuario.cadastro.controller.js
git add Acerva.Web/Views/Home/Index.cshtml
git add Acerva.Web/Views/Regional/_CadastroRegional.cshtml
git add Acerva.Web/Views/Shared/_Layout.cshtml
git add Acerva.Web/Views/Shared/_LoginPartial.cshtml
git add Acerva.Web/Views/Situacao/Index.cshtml
git add Acerva.Web/Views/Usuario/_CadastroUsuario.cshtml
git add Acerva.Web/Web.config
git add scripts/acerva.sql